export default Object.freeze({
  LOGIN: 'Login',
  SIGNUP: 'SignUp',
  SIGNUP_STEP2: 'SignUpStep2',
  FORGOT_PASSWORD: 'forgotPassword',
  PASSWORD_RESET_OTP: 'passwordResetOTP',
  PASSWORD_RESET: 'passwordReset',
  SIGNUP_VERIFICATION: 'signupVerification',
  FEED: 'NewsFeed',
  ADD_POST: 'AddPost',
  ACCOUNT: 'Account',
  KEEP_HANG: 'KEEP_HANG',
  USER_PROFILE: 'UserProfile',
  MESSAGES: 'Messages',
  MY_REELS: 'MyReels',
  ADD_COMMENT_REEL: 'ADD_COMMENT_REEL', 
  SWAP: 'Swap',
  EDIT_PROFILE: 'EditProfile',
  ACTIVITY: 'Activity',
  GROUPS: 'Groups',
  GROUP_FEED: 'GroupFeed',
  EDIT_GROUP:'EDIT_GROUP',
  COMMENTS: 'Comments',
  ALL_FRIENDS: 'AllFriends',
  Add_NEW_FRIEND: 'AddNewFriend',
  RECEIVED_REQUESTS: 'ReceivedRequests',
  SENT_REQUESTS: 'SentRequests',
  CREATE_NEW_GROUP: 'CreateNewGroup',
  SET_GROUP_PHOTO: 'SetGroupPhoto',
  UPDATE_GROUP_PHOTO: 'UPDATE_GROUP_PHOTO',
  MY_GROUPS: 'MY_GROUPS',
  MEMBER_REQUEST: 'MEMBER_REQUEST',
  LIST_OF_MEMBERS: 'LIST_OF_MEMBERS',
  INVITE_GROUP_MEMBERS: 'InviteGroupMembers',
  SET_POST_AUDIENCE: 'SetPostAudience',
  MESSAGES_NAVIGATOR: 'MessagesNavigator',
  CHAT_ROOM: 'ChatRoom',
  SETTING_PRIVACY: 'SettingPrivacy',
  ACTIVITY_NAVIGATOR: 'ActivityNavigator',
  GROUP_NAVIGATOR: 'GroupNavigator',
  SWAP_DISPLAY: 'SwapDisplay',
  SWAP_SHIPPING: 'SwapShipping',
  SWAP_CHECKOUT: 'SwapCheckout',
  SWAP_CHECKOUT_COMPLETE: 'SwapCheckoutComplete',
  ADDS_STORY: 'AddStory',
  STORY_VIEW_SCREEN: 'StoryViewScreen',
  ADD_NEW_REEL: 'ADD_NEW_REEL',
  REEL_PLAYER: 'ReelPlayer',
  APP_NAVIGATOR: 'AppNavigator',
  TAG_PEOPLE: 'TagPeople',
  FEELING_ACTIVITY: 'feelingAndActivity',
  SEARCH_SCREEN:'SearchScreen',
  SAVED_POST_SCREEN: 'HangFlowScreen',
  PERSONAL_INFORMATION:"PERSONAL_INFORMATION",
  UPDATE_NAME:'UPDATE_NAME',
  UPDATE_EMAIL:'UPDATE_EMAIL',
  MANAGE_EMAIL:'MANAGE_EMAIL',
  UPDATE_PHONE_NUMBER:'UPDATE_PHONE_NUMBER',
  UPDATE_DOB:'UPDATE_DOB',
  UPDATE_GENDER:'UPDATE_GENDER',
  POST_DETAILS_SCREEN:'PostDetailScreen'

});
