export default {
  LOGIN: 'login',
  SIGNUP: 'signup',
  SIGNUP_STEP_TWO: 'signupStepTwo',
  SIGNUP_STEP_THREE: 'signupStepThree',
  SIGNUP_STEP_FOUR: 'signupStepFour',
  PASSWORD_RESET_STEP_ONE: 'passwordResetStepOne',
  PASSWORD_RESET_STEP_TWO: 'passwordResetStepTwo',
  PASSWORD_RESET_STEP_THREE: 'passwordResetStepThree',
  APP_NAVIGATOR: 'appNavigator',
  COMMENTS: 'comments',
  ADDS_STORY: 'AddsStory',
  ADD_NEW_REEL: 'addNwReel',
  ADD_POST: 'addPost',
  TAG_PEOPLE: 'tagPeople',
  FEELING_ACTIVITY: 'feelingActivity',
  MESSAGES_NAVIGATOR: 'messageNavigator',
  STORY_VIEW_SCREEN: 'storyViewScreen',
  REEL_PLAYER: 'reelPlayer',
};
